### ISSUE TITLE
Website: Improve Feature Hub introduction

### ISSUE THREAD

**Issue by clebert** [sinnerschrader/feature-hub#332]
Question: Why do we mention here (https://feature-hub.io/docs/getting-started/introduction) exactly the two packages (react & core)?

Maybe we should change the introductory sentence from

> “The Feature Hub includes a collection of npm packages that when used together provide a full-fledged solution for composing micro frontends:”

 to

> “The Feature Hub includes two core packages that when used together provide a full-fledged solution for composing micro frontends:”

**Comment by HannesT117** [comment]
Hi @clebert, regarding the documentation of FeatureHub: I came across this repository and had some questions left. Could you elaborate a little bit more on how a FeatureApp is supposed to be built, so that a FeatureAppLoader can access it?

Being a little bit more specific: [There's a line on the page about integrating apps](https://feature-hub.io/docs/guides/integrating-the-feature-hub#placing-feature-apps-on-a-web-page-using-react), `<FeatureAppLoader src="https://example.com/some-feature-app.js" />`. In demos/ I saw furthermore that you have some adjustments to the base configuration of webpack. With this in mind, the documentation could answer the following questions regarding the FeatureAppLoader:

* What configuration of webpack is necessary for the FeatureApp (being developed using a different repository than the FeatureHub) to get the example above to work?
* Is it possible to just use a create-react-app with few improvements as FeatureApp (without ejecting)?
* Do you have experience using apps bundled with Parcel, for example?
