### ISSUE TITLE
update documentation code snippets to TypeScript

### ISSUE THREAD

**Issue by terabaud** [sinnerschrader/feature-hub#619]
It's extremely hard to get the typings right when you go through the documentation.
For example, it's not super intuitive what you have to provide in the `<>` when writing a
feature service without looking at the demo projects. 

```js
export interface MyFeatureServiceManagerV1 {
  sayHello: () => void;
}

class MyFeatureServiceV1Impl implements MyFeatureServiceManagerV1 {
  sayHello() { console.log('Hello World'); }
}

export interface MySharedFeatureServiceManager extends SharedFeatureService {
  readonly '1.0.0': FeatureServiceBinder<MyFeatureServiceManagerV1>
}

export const MyFeatureServiceDefinition: FeatureServiceProviderDefinition<MySharedFeatureServiceManager> { 
  id: 's2:my-feature-service',
  create() {
    const featureService = new MyFeatureServiceManagerV1Impl();
    return { '1.0.0': () => ({featureService})}
  }
}
```

**Comment by unstubbable** [comment]
Using JavaScript (as opposed to TypeScript) in our documentation is an intentional tradeoff that we thought would allow for more inclusivity, since you don't need to be familiar with the TS syntax to understand the examples. If a reader is indeed intending not to only read/understand the examples, but also wants to start coding, we recommend to dive into the demos (see yellow boxes at the top of the pages), as you apparently also have done successfully. 👍

To get more details about required type params for example, I would recommend to use your editor of choice to navigate through the typings or have a look at https://feature-hub.io/@feature-hub/ for the web version of the (typed) API documentation.
