### ISSUE TITLE
How to integrate a feature app into another feature app using FeatureAppLoader?

### ISSUE THREAD

**Issue by AndresHMosqueda** [sinnerschrader/feature-hub#654]
I need some clarity on how to integrate a feature app into another feature app by using FeatureAppLoader?

Let say that I have the child app which is running on isolation in locahost:3000 (https://github.com/AndresHMosqueda/feature-child-app) and I want to display it inside the container app(https://github.com/AndresHMosqueda/feature-container-app) which I need to be running on  localhost:3002

![Screen Shot 2021-03-25 at 13 56 09](https://user-images.githubusercontent.com/42881305/112535415-e489f780-8d71-11eb-9d98-fff3210b596e.png)

This is the error I'm having:

```
index.js:1 The Feature App for the src "http://localhost:3000" and the ID "test:hello-featureApp" could not be rendered. Error: Fetching http://localhost:3000
    at HTMLScriptElement.s (system-production.js:4)
```

What am I missing??

**Comment by unstubbable** [comment]
As mentioned in https://github.com/sinnerschrader/feature-hub/issues/653#issuecomment-807339576, you need to point the `src` at a JavaScript file. Specifically, since you are integrating for the client here, using the AMD module loader, you need to provide an AMD module  that contains the Feature App definition, as documented at https://feature-hub.io/docs/guides/integrating-the-feature-hub#src. CRA does not automagically create this bundle for you. You probably need to eject, to configure this extra bundle in the webpack config  (using `client/src/components/HelloComponent.js` as entry). But I’m not too familiar with CRA to give you any more pointers than that.

**Comment by AndresHMosqueda** [comment]
Ok thanks, it's more clear to me, what's the meaning of CRA?? @unstubbable

**Comment by unstubbable** [comment]
CRA is a common abbreviation of "Create React App".

**Comment by AndresHMosqueda** [comment]
@unstubbable I got this error: What does this exactly mean?

 index.js:1 The Feature App for the src "http://localhost:3004/someLibName.js" and the ID "test:hello-featureApp" could not be rendered. Error: Cannot find module 'node'

`http://localhost:3004/someLibName.js` is in this repo (https://github.com/AndresHMosqueda/featureApp)
container/integrator app is in this repo (https://github.com/AndresHMosqueda/feature-container-app)

Can you please help me to explain what's happening?

**Comment by unstubbable** [comment]
Compare those two lines and spot the difference:

https://github.com/AndresHMosqueda/feature-container-app/blob/23e0b1666b8c7f732e35bc38ca63b0d2fc8933cd/src/index.js#L15

https://github.com/AndresHMosqueda/featureApp/blob/cb7c2cfcfd84bb63dfcf322560e1ff74e85d64d3/src/index.js#L15

I’m sorry, but I’m going to close this now.  This issue tracker is not a place to get free dev support. If you need help debugging your JavaScript applications, you should consider other resources.
